name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1     
      - name: set up JDK 1.8     
        uses: actions/setup-java@v1       
        with:         
           java-version: 1.8
      - name: install npm
        run: |
         npm install
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          java-version: 8
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build
        run: |
          ionic cordova build android --prod

