name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Universal APK Builder
      uses: skywall/universal-apk-builder@v1.0.1

