name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: React Native Android Build APK
        uses: realabbas/Github-Actions-React-Native@v1.1.2


