name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1     
      - name: Build the app
        run: ./gradlew build

