name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.0.0

