name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Publish Debug APK
        uses: ShaunLWM/action-release-debugapk@0.0.7



