name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Trigger Mobile Builds with Appflow
       uses: ionic-team/appflow-build@v1






