name: BuildAndroid

on:
 push:
  branches:
   - main 
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: automated-build-android-app-with-github-action
    - uses: amirisback/automated-build-android-app-with-github-action@2.0.1
